### PR TITLE
Add dynamics field

### PR DESCRIPTION
**Pull request by killzoner**
Hi there.

I have been searching for a decently configurable crate for `tracing` in JSON, unfortunately the default one has very few options.
I turns out yours, while aimed at logback is much more flexible.

I'm having a use case where I need to add constant fields (for which `with_constants` is a perfect match), and I also have the need for a key "time" instead of "@timestamp" on all records.

I added `with_dynamics` to allow that and that makes this crate a very general purpose JSON formatter for `tracing` while defaulting to lockback format.

I have been wondering if it would be better to have `Serialize` from `serde` in `with_dynamics` signature, but googling a few time gave me only "you can't add bound trait in function signatures".

Happy to discuss the matter!

### CODE REVIEW

**Comment by killzoner** [comment]
Tagging @gsson as I'm not sure you get notification without reviewer or assignee on the PR (sorry if it did)

**Comment by killzoner** [comment]
Thanks a lot. I fixed the lint issue in the meantime

**Comment by killzoner** [comment]
I did some other PR trying to adjust to your suggestion here https://github.com/gsson/tracing-logstash/pull/13

**Comment by gsson** [comment]
I'm taking a bit of a lunch break now so I took a proper look :)

Code looks pretty good, but one thing you mentioned originally;

> I have been wondering if it would be better to have Serialize from serde in with_dynamics signature, but googling a few time gave me only "you can't add bound trait in function signatures".

It would be nice to be able to serialize arbitrary types, and potentially reduce allocations by not having to allocate separate `String`/`Vec` objects 🤔 

I did a quick prototype that seems to do something; [I posted a separate PR for it](https://github.com/gsson/tracing-logstash/pull/14)

Do you think that could do what you wanted? There's an example usage in the tests, but consider it a draft for now

**Comment by killzoner** [comment]
Hello @gsson your PR is actually what I would have liked to do in the first place, it's just my Rust is a bit limited rn as it's not my day to day language :sweat_smile: 

This would be a great addition and avoid allocations at the same time compared to my proposal

**Comment by killzoner** [comment]
Closing in favor of https://github.com/gsson/tracing-logstash/pull/13

**Comment by gsson** [comment]
@killzoner: Just released this in 0.7.0, give it a go and let me know how it works out!

**Comment by killzoner** [comment]
Hey @gsson 

I already adapted from your branch earlier today and it works well.

Plus, you get handling of nested constant values out of the box, which is really nice.

Will do the switch asap to released version

Thank you very much !

**Pull request closed without merging**
